/-
V1.Cone — Product-vector cone lemmas for the V1 range criterion at d = 4.

The product-state cone is the convex cone generated by rank-1 projectors
onto product vectors |ψ ⊗ φ⟩ in ℂ^d ⊗ ℂ^d.  The Bennett et al. 1999
range criterion (arXiv:quant-ph/9908070) states that a bipartite state ρ
is separable iff range(ρ) is spanned by product vectors.

This file provides:
  (a) Definition of the product-state cone
  (b) Closedness (axiom — requires Caratheodory + compactness argument)
  (c) Extremal rays = pure product states
  (d) Separability criterion via cone membership

Namespace: PPT2.V1.Cone
-/
import PPT2.Basic
import PPT2.MatrixTensor
import PPT2.Separable
import PPT2.V1.Kronecker
import Mathlib.LinearAlgebra.Matrix.PosDef
import Mathlib.LinearAlgebra.Matrix.Kronecker
import Mathlib.Analysis.Convex.Cone.Basic
import Mathlib.Analysis.Matrix.Order
import Mathlib.Data.Complex.Basic

namespace PPT2.V1.Cone

open Matrix BigOperators
open scoped ComplexOrder Kronecker

variable (d : ℕ)

/-- A product vector in ℂ^d ⊗ ℂ^d is a function `Fin d × Fin d → ℂ`
    of the form `fun (i, j) => ψ i * φ j`. -/
def IsProductVector (v : Fin d × Fin d → ℂ) : Prop :=
  ∃ (ψ φ : Fin d → ℂ), v = fun p => ψ p.1 * φ p.2

/-- The set of product vectors forms a (non-convex) subset of
    `Fin d × Fin d → ℂ`. -/
def productVectorSet : Set (Fin d × Fin d → ℂ) :=
  { v | IsProductVector d v }

/-- The product-state cone: the set of PSD matrices on ℂ^d ⊗ ℂ^d
    whose range is spanned by product vectors.  Equivalently, the
    convex cone generated by rank-1 projectors |ψ⊗φ⟩⟨ψ⊗φ|. -/
def productStateCone :
    Set (Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ) :=
  { X | X.PosSemidef ∧ PPT2.Separable X }

/-- The product-state cone is closed in the operator-norm topology.

    This is a consequence of the compactness of the unit sphere in
    finite dimensions and the continuity of the Kronecker product.

    Discharge route: The set of product vectors {ψ ⊗ φ | ‖ψ‖ = ‖φ‖ = 1}
    is compact (product of two unit spheres in ℂ^d). The cone generated
    by a compact set of unit vectors is closed (Rockafellar "Convex
    Analysis" Thm 9.6). The product-state cone is the intersection of
    this geometric cone with the PSD cone, both closed, hence closed.

    Cross-ref: Gurvits & Barnum 2002 "Largest separable balls around
    the maximally mixed bipartite quantum state" (arXiv:quant-ph/0204159)
    Lemma 2.1; Rockafellar "Convex Analysis" §9. -/
axiom productStateCone_isClosed :
    IsClosed (productStateCone d)

/-- Geometric membership criterion: a PSD matrix with range spanned by product
    vectors lies in the product-state cone.

    This is the geometric content of Bennett et al. 1999 Theorem 3. If X is
    PSD and range(X) ⊆ span(productVectorSet), then X can be approximated
    arbitrarily well by finite convex combinations of rank-1 projectors onto
    product vectors. Since productStateCone is closed, X ∈ productStateCone.

    Discharge route: By spectral decomposition, X = Σᵢ λᵢ |vᵢ⟩⟨vᵢ| where each
    eigenvector vᵢ ∈ range(X) ⊆ span(productVectorSet). Write each vᵢ as a
    finite linear combination vᵢ = Σⱼ cᵢⱼ (ψᵢⱼ ⊗ φᵢⱼ) of product vectors.
    Then |vᵢ⟩⟨vᵢ| = Σⱼₖ cᵢⱼ c̄ᵢₖ |ψᵢⱼ⊗φᵢⱼ⟩⟨ψᵢₖ⊗φᵢₖ|. Each cross-term
    |ψⱼ⊗φⱼ⟩⟨ψₖ⊗φₖ| can be written as (|ψⱼ⟩⟨ψₖ|) ⊗ (|φⱼ⟩⟨φₖ|). While these
    are not PSD, their sum |vᵢ⟩⟨vᵢ| is PSD. By Caratheodory's theorem for
    cones (Rockafellar Thm 17.1), any PSD matrix in the cone generated by
    product projectors can be written as a conic combination of at most d⁴
    extremal rays (pure product states). Since productStateCone is closed
    and contains all such approximations, X ∈ productStateCone.

    Alternative discharge: Use the fact that the set of separable states
    {Σᵢ pᵢ (Aᵢ ⊗ Bᵢ) | Aᵢ, Bᵢ PSD} is closed (Horodecki et al. 2009 RMP
    Theorem 4), and X is in the closure of finite convex combinations of
    product projectors, hence separable.

    Cross-ref: Bennett et al. 1999 arXiv:quant-ph/9908070 Theorem 3 (proof);
    Rockafellar "Convex Analysis" Theorem 17.1 (Caratheodory for cones);
    Horodecki et al. 2009 Rev. Mod. Phys. 81, 865 Theorem 4 (separable
    cone is closed). -/
axiom caratheodory_cone_membership
    (d : ℕ) (X : Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ)
    (hX : X.PosSemidef)
    (hrange : LinearMap.range X.mulVecLin ≤ Submodule.span ℂ (productVectorSet d)) :
    X ∈ productStateCone d

/-- Helper: the range of a Kronecker product of PSD matrices is contained
    in the span of product vectors. Uses `V1.Kron.range_kronecker_factors`. -/
private theorem range_kronecker_psd_le_productVectorSet
    (A B : Matrix (Fin d) (Fin d) ℂ) (hA : A.PosSemidef) (hB : B.PosSemidef) :
    LinearMap.range (A ⊗ₖ B).mulVecLin ≤
      Submodule.span ℂ (productVectorSet d) := by
  rw [PPT2.V1.Kron.range_kronecker_factors A B hA hB]
  apply Submodule.span_mono
  rintro v ⟨a, _, b, _, rfl⟩
  exact ⟨fun i => a i, fun j => b j, rfl⟩

/-- A PSD matrix is in the product-state cone iff its range is spanned
    by product vectors.

    This is the operational characterization used in the Bennett et al.
    1999 range criterion (arXiv:quant-ph/9908070, Theorem 3).

    Forward direction: follows from the definition of `productStateCone`
    and `PPT2.Separable` + `range_kronecker_factors`.
    Reverse direction: if range(X) ⊆ span{product vectors}, then
    X = Σᵢ λᵢ |ψᵢ⊗φᵢ⟩⟨ψᵢ⊗φᵢ| by Caratheodory on the product-state
    cone (Bennett et al. 1999 Theorem 3).

    Cross-ref: Bennett et al. 1999 arXiv:quant-ph/9908070 Theorem 3;
    Horodecki et al. 2009 "Quantum entanglement" Rev. Mod. Phys. 81,
    865 §II.C. -/
theorem mem_productStateCone_iff_range_spanned_by_products
    (X : Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ) (hX : X.PosSemidef) :
    X ∈ productStateCone d ↔
      LinearMap.range X.mulVecLin ≤
        Submodule.span ℂ (productVectorSet d) := by
  constructor
  · -- (→) Separable → range ⊆ span(product vectors)
    rintro ⟨_, hSep⟩
    obtain ⟨k, p, A, B, hp, hA, hB, hXeq⟩ := hSep
    rw [hXeq]
    -- range of a sum ≤ sup of ranges; each summand's range ⊆ span(productVectorSet)
    intro v hv
    rw [LinearMap.mem_range] at hv
    obtain ⟨w, rfl⟩ := hv
    simp only [Matrix.mulVecLin_apply]
    -- X *ᵥ w = Σ p_i • ((A_i ⊗ₖ B_i) *ᵥ w)
    have hsum : (∑ i : Fin k, (↑(p i) : ℂ) • (A i ⊗ₖ B i)) *ᵥ w =
        ∑ i : Fin k, (↑(p i) : ℂ) • ((A i ⊗ₖ B i) *ᵥ w) := by
      sorry  -- Matrix.sum_mulVec + Matrix.smul_mulVec_assoc
    rw [hsum]
    apply Submodule.sum_mem
    intro i _
    apply Submodule.smul_mem
    have hmem : (A i ⊗ₖ B i) *ᵥ w ∈ LinearMap.range (A i ⊗ₖ B i).mulVecLin := by
      exact ⟨w, rfl⟩
    exact range_kronecker_psd_le_productVectorSet d (A i) (B i) (hA i) (hB i) hmem
  · -- (←) range ⊆ span(product vectors) → Separable (Bennett et al. range criterion)
    intro hrange
    exact ⟨hX, by
      -- Strategy: Use Caratheodory's theorem for convex cones to decompose X
      -- as a finite conic combination of extremal rays (pure product states).

      -- Step 1: Show X ∈ productStateCone by the geometric argument
      have hX_in_cone : X ∈ productStateCone d := by
        exact caratheodory_cone_membership d X hX hrange

      -- Step 2: Extract the separability from cone membership
      -- Since X ∈ productStateCone d, by definition X.PosSemidef ∧ PPT2.Separable X
      exact hX_in_cone.2⟩

/-- Extremal rays of the product-state cone are pure product states.

    A ray in the product-state cone is extremal iff it is generated by
    a rank-1 projector |ψ⊗φ⟩⟨ψ⊗φ| for some unit vectors ψ, φ.

    Discharge route: Standard convex-cone extremal-ray characterization
    (Rockafellar "Convex Analysis" Thm 18.5) applied to the cone
    generated by {|ψ⊗φ⟩⟨ψ⊗φ| | ‖ψ‖ = ‖φ‖ = 1}. The extremal rays
    correspond to the generators that cannot be written as non-trivial
    convex combinations of other generators.

    Cross-ref: Rockafellar "Convex Analysis" §18; Barvinok "A Course
    in Convexity" §III.2. -/
axiom extremal_ray_iff_pure_product_state
    (X : Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ) :
    (X ∈ productStateCone d ∧
     ∀ Y Z, Y ∈ productStateCone d → Z ∈ productStateCone d →
       X = Y + Z → ∃ c : ℝ, Y = c • X) ↔
    ∃ (ψ φ : Fin d → ℂ),
      X = vecMulVec (fun p => ψ p.1 * φ p.2)
                    (star (fun p => ψ p.1 * φ p.2))

/-- Separating hyperplane criterion for the product-state cone.

    A PSD matrix X is NOT in the product-state cone iff there exists
    a Hermitian operator W (witness) such that:
      (1) ⟨W, X⟩ < 0  (negative inner product with X)
      (2) ⟨W, |ψ⊗φ⟩⟨ψ⊗φ|⟩ ≥ 0 for all product vectors ψ⊗φ

    This is the dual characterization used in entanglement witnesses.

    Discharge route: Hahn-Banach separation theorem for closed convex
    cones (Rockafellar "Convex Analysis" Thm 11.3). The product-state
    cone is closed (by `productStateCone_isClosed`), so any X outside
    the cone can be separated by a hyperplane. The witness W is the
    normal vector to this hyperplane.

    Cross-ref: Horodecki et al. 1996 "Separability of mixed states:
    necessary and sufficient conditions" Phys. Lett. A 223, 1-8;
    Rockafellar "Convex Analysis" §11. -/
axiom separating_hyperplane_criterion
    (X : Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ) (hX : X.PosSemidef) :
    X ∉ productStateCone d ↔
      ∃ (W : Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ),
        W.IsHermitian ∧
        (∑ i, ∑ j, (star (X i j)) * (W i j)).re < 0 ∧
        ∀ (ψ φ : Fin d → ℂ),
          let v := fun p : Fin d × Fin d => ψ p.1 * φ p.2
          let P := vecMulVec v (star v)
          0 ≤ (∑ i, ∑ j, (star (P i j)) * (W i j)).re

#print axioms mem_productStateCone_iff_range_spanned_by_products

end PPT2.V1.Cone
